name: Build
on:
  workflow_call:
  workflow_dispatch:
  
jobs:
  build:
    name: Build ex2
    runs-on: ubuntu-latest
    
    steps:
      - name: Build
        run: |
          echo Hello World > hello.txt

      - uses: actions/upload-artifact@master
        name: Upload artifact
        with:
          name: hello.txt
          path: hello.txt
