name: Build
on:
  workflow_call:
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: gh repo sync $REPOSITORY -b $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: main

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: sync
    
    steps:
      - name: Build
        run: |
          echo Hello World > hello.txt

      - uses: actions/upload-artifact@master
        name: Upload artifact
        with:
          name: hello.txt
          path: hello.txt
