name: Build
on:
  workflow_call:
  workflow_dispatch:
  
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Sync repo
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.mergeUpstream({
              owner: 'org-anic',
              repo: 'testwf',
              branch: 'main',
            });
  build:
    name: Build ex3
    runs-on: ubuntu-latest
    needs: sync
    
    steps:
      - name: Build
        run: |
          echo Hello World > hello.txt

      - uses: actions/upload-artifact@master
        name: Upload artifact
        with:
          name: hello.txt
          path: hello.txt
