name: test-run-on

on:
  workflow_dispatch

jobs:

  build:
    name: Do the job
  
    strategy:
      matrix:
        arch: [Win32, x64]

    runs-on: ${{ matrix.arch == 'x64' && 'ubuntu-latest' || 'windows-2022' }}

    steps:
      - name: Print
        run: |
          echo ${{ runner.OS }}
