name: Test A
on:
  workflow_dispatch:
  
jobs:
  build:
    name: Trigger build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Test
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          bash ./script.sh "${{ env.SECRET }}"

          python3 ./script.py



