name: Trigger build
on:
  workflow_dispatch:
  
jobs:
  build:
    name: Trigger build
    runs-on: ubuntu-latest
    
    steps:
      - name: Sync repo
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.repos.mergeUpstream({
              owner: 'org-anic',
              repo: 'testwf',
              branch: 'main',
            });
      - name: Trigger build
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'org-anic',
              repo: 'testwf',
              workflow_id: 'build.yml',
              ref: 'main',
            });
