name: Trigger build
on:
  workflow_dispatch:
  
jobs:
  build:
    name: Trigger build
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger build
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/org-anic/testwf/actions/workflows/build.yaml/dispatches --data '{"ref": "master"}'
            
